import { type Column } from '@/components/sections/data-table';
import { type ComparisonData } from '@/components/sections/templates';

export const PAGE_HEADER = {
  title: 'Equipments',
  description:
    'Our company has been dedicated to providing high-quality injection molding services since 2005. Over the years, we have grown from a small mold-making company to a comprehensive manufacturing enterprise that offers a wide range of services.',
  action: {
    text: 'Overwhelmed by Data? Let Zetar Make the Decision',
    href: '/contact',
  },
};

// TABLE DATA
export const MOLD_MAKING = {
  title: (
    <>
      Mold Making <span className="text-primary">Equipments</span>
    </>
  ),
  description:
    'Our in-house injection mold manufacturing facility is fully equipped with all the necessary mold making machines, including CNC Machines, Wire Cutters, Drilling Machines, EDMs, Grinders, Millers, Precision Engravers, and Slow Wire Cutters. With this comprehensive setup, we’re able to consistently deliver more than 100 sets of mold each month.',
  action: {
    text: 'Overwhelmed by Data? Let Zetar Make the Decision',
    href: '/contact',
  },
};

export const MOLD_MAKING_COLUMNS: Column<ComparisonData>[] = [
  {
    header: 'No.',
    accessorKey: 'no',
  },
  {
    header: 'Equipments',
    accessorKey: 'equipments',
  },
  {
    header: 'Brand',
    accessorKey: 'brand',
  },
  {
    header: 'Model',
    accessorKey: 'model',
  },
  {
    header: 'Quantity (units)',
    accessorKey: 'quantity',
  },
  {
    header: 'Usage Area',
    accessorKey: 'usageArea',
  },
];

export const MOLD_MAKING_DATA: ComparisonData[] = [
  {
    no: '1',
    equipments: 'Milling Machine',
    brand: 'Fengbao',
    model: 'FTM-4TA',
    quantity: '1',
    usageArea: 'Mold Workshop',
  },
  {
    no: '2',
    equipments: 'Milling Machine',
    brand: 'Qiao Jin',
    model: '4SA',
    quantity: '1',
    usageArea: 'Mold Workshop',
  },
  {
    no: '3',
    equipments: 'Milling Machine',
    brand: 'Jieyongda',
    model: 'JOINT-4VA',
    quantity: '2',
    usageArea: 'Mold Workshop',
  },
  {
    no: '4',
    equipments: 'Large Grinder',
    brand: 'Rongde',
    model: 'KGS-84AHK',
    quantity: '1',
    usageArea: 'Mold Workshop',
  },
  {
    no: '5',
    equipments: 'Small Grinder',
    brand: 'Yintai',
    model: '450',
    quantity: '1',
    usageArea: 'Mold Workshop',
  },
  {
    no: '6',
    equipments: 'Small Grinder',
    brand: 'Rongde',
    model: 'KGS-618M',
    quantity: '2',
    usageArea: 'Mold Workshop',
  },
  {
    no: '7',
    equipments: 'Precision Grinder',
    brand: 'Yuqing',
    model: 'LSG-52AS',
    quantity: '1',
    usageArea: 'Mold Workshop',
  },
  {
    no: '8',
    equipments: 'Drilling Machine',
    brand: 'Hongchang',
    model: 'HC-900DS',
    quantity: '1',
    usageArea: 'Mold Workshop',
  },
  {
    no: '9',
    equipments: 'Lathe',
    brand: 'Yunji',
    model: 'G6132*1000',
    quantity: '1',
    usageArea: 'Mold Workshop',
  },
  {
    no: '10',
    equipments: 'Precision Engraver',
    brand: 'Jiatie',
    model: 'JTGK-500',
    quantity: '1',
    usageArea: 'Mold Workshop',
  },
  {
    no: '11',
    equipments: 'Precision Engraver',
    brand: 'Jiatie',
    model: 'JTGK-750',
    quantity: '1',
    usageArea: 'Mold Workshop',
  },
  {
    no: '12',
    equipments: 'Machining Center',
    brand: 'Shangfeng',
    model: 'SF-850',
    quantity: '1',
    usageArea: 'Mold Workshop',
  },
  {
    no: '13',
    equipments: 'Machining Center',
    brand: 'Xinyan',
    model: 'XY1580',
    quantity: '1',
    usageArea: 'Mold Workshop',
  },
  {
    no: '14',
    equipments: 'Machining Center',
    brand: 'Makino',
    model: 'MAKINOF5',
    quantity: '1',
    usageArea: 'Mold Workshop',
  },
  {
    no: '15',
    equipments: 'EDM Machine',
    brand: 'Dimeng',
    model: 'F2-50',
    quantity: '2',
    usageArea: 'Mold Workshop',
  },
  {
    no: '16',
    equipments: 'EDM Machine',
    brand: 'Pules',
    model: 'AP50',
    quantity: '1',
    usageArea: 'Mold Workshop',
  },
  {
    no: '17',
    equipments: 'Punching Machine',
    brand: 'Changkai',
    model: 'CK340',
    quantity: '1',
    usageArea: 'Mold Workshop',
  },
  {
    no: '18',
    equipments: 'Wire Cut EDM',
    brand: 'Ruijun',
    model: 'FR500G',
    quantity: '1',
    usageArea: 'Mold Workshop',
  },
  {
    no: '19',
    equipments: 'Wire Cut EDM',
    brand: 'Ruijun',
    model: 'FR700S',
    quantity: '1',
    usageArea: 'Mold Workshop',
  },
  {
    no: '20',
    equipments: 'Slow Wire Cut EDM',
    brand: 'Sodick',
    model: 'AQ400LS',
    quantity: '1',
    usageArea: 'Mold Workshop',
  },
  {
    no: '21',
    equipments: 'EDM Machine',
    brand: 'Makino',
    model: 'EDGE3I',
    quantity: '1',
    usageArea: 'Mold Workshop',
  },
  {
    no: '22',
    equipments: 'EDM Machine',
    brand: 'Makino',
    model: 'EDNC65',
    quantity: '1',
    usageArea: 'Mold Workshop',
  },
  {
    no: '23',
    equipments: 'Precision Engraver',
    brand: 'Beijing Jingdiao',
    model: '400TE',
    quantity: '1',
    usageArea: 'Mold Workshop',
  },
];

// TABLE DATA
export const INJECTION_PRODUCTION = {
  title: (
    <>
      Injection Production <span className="text-primary">Equipments</span>
    </>
  ),
  description:
    'We currently have 35 injection molding machines, with six of them housed in a Class M8 dust-free room. Additionally, we have facilities for assembly and logo printing. Our largest machine, an 1850T, can handle parts weighing up to 10 kg.',
  action: {
    text: 'Overwhelmed by Data? Let Zetar Make the Decision',
    href: '/contact',
  },
};
export const INJECTION_PRODUCTION_COLUMNS: Column<ComparisonData>[] = [
  {
    header: 'No.',
    accessorKey: 'no',
  },
  {
    header: 'Brand',
    accessorKey: 'brand',
  },
  {
    header: 'Machine Tonnage (T)',
    accessorKey: 'machineTonnage',
  },
  {
    header: 'Injection Volume (g)',
    accessorKey: 'injectionVolume',
  },
  {
    header: 'Quantity (units)',
    accessorKey: 'quantity',
  },
  {
    header: 'Usage Area',
    accessorKey: 'usageArea',
  },
];

export const INJECTION_PRODUCTION_DATA: ComparisonData[] = [
  {
    no: '1',
    brand: 'FengTie',
    machineTonnage: '90T',
    injectionVolume: '90g',
    quantity: '1',
    usageArea: 'Injection Workshop',
  },
  {
    no: '2',
    brand: 'FengTie',
    machineTonnage: '120T',
    injectionVolume: '200g',
    quantity: '1',
    usageArea: 'Injection Workshop',
  },
  {
    no: '3',
    brand: 'LiGuang',
    machineTonnage: '90T',
    injectionVolume: '95g',
    quantity: '1',
    usageArea: 'Injection Workshop',
  },
  {
    no: '4',
    brand: 'FANUC',
    machineTonnage: '100T',
    injectionVolume: '147g',
    quantity: '1',
    usageArea: 'Injection Workshop',
  },
  {
    no: '5',
    brand: 'SUMITOMO',
    machineTonnage: '160T',
    injectionVolume: '¢22mm:50g',
    quantity: '1',
    usageArea: 'Injection Workshop',
  },
  {
    no: '6',
    brand: 'SUMITOMO',
    machineTonnage: '250T',
    injectionVolume: '¢28mm:100g',
    quantity: '1',
    usageArea: 'Injection Workshop',
  },
  {
    no: '7',
    brand: 'Chen Hsong',
    machineTonnage: '120T',
    injectionVolume: '153g',
    quantity: '1',
    usageArea: 'Injection Workshop',
  },
  {
    no: '8',
    brand: 'Chen Hsong',
    machineTonnage: '128T',
    injectionVolume: '209g',
    quantity: '5',
    usageArea: 'Injection Workshop',
  },
  {
    no: '9',
    brand: 'Chen Hsong',
    machineTonnage: '150T',
    injectionVolume: '260g',
    quantity: '2',
    usageArea: 'Injection Workshop',
  },
  {
    no: '10',
    brand: 'Chen Hsong',
    machineTonnage: '168T',
    injectionVolume: '304g',
    quantity: '4',
    usageArea: 'Injection Workshop',
  },
  {
    no: '11',
    brand: 'Chen Hsong',
    machineTonnage: '178T',
    injectionVolume: '310g',
    quantity: '1',
    usageArea: 'Injection Workshop',
  },
  {
    no: '12',
    brand: 'Chen Hsong',
    machineTonnage: '208T',
    injectionVolume: '275g',
    quantity: '6',
    usageArea: 'Injection Workshop',
  },
  {
    no: '13',
    brand: 'YIZUMI',
    machineTonnage: '200T',
    injectionVolume: '476g',
    quantity: '1',
    usageArea: 'Injection Workshop',
  },
  {
    no: '14',
    brand: 'FANUC',
    machineTonnage: '220T',
    injectionVolume: '211g',
    quantity: '1',
    usageArea: 'Injection Workshop',
  },
  {
    no: '15',
    brand: 'YIZUMI',
    machineTonnage: '200T',
    injectionVolume: '280g',
    quantity: '1',
    usageArea: 'Injection Workshop',
  },
  {
    no: '16',
    brand: 'Chen Hsong',
    machineTonnage: '228T',
    injectionVolume: '300g',
    quantity: '1',
    usageArea: 'Injection Workshop',
  },
  {
    no: '17',
    brand: 'YIZUMI',
    machineTonnage: '250T',
    injectionVolume: '406g',
    quantity: '1',
    usageArea: 'Injection Workshop',
  },
  {
    no: '18',
    brand: 'YIZUMI',
    machineTonnage: '300T',
    injectionVolume: '406g',
    quantity: '1',
    usageArea: 'Injection Workshop',
  },
  {
    no: '19',
    brand: 'FANUC',
    machineTonnage: '300T',
    injectionVolume: '280g',
    quantity: '1',
    usageArea: 'Injection Workshop',
  },
  {
    no: '20',
    brand: 'FANUC',
    machineTonnage: '300T',
    injectionVolume: '550g',
    quantity: '1',
    usageArea: 'Injection Workshop',
  },
  {
    no: '21',
    brand: 'Chen Hsong',
    machineTonnage: '258T',
    injectionVolume: '382g',
    quantity: '1',
    usageArea: 'Injection Workshop',
  },
  {
    no: '22',
    brand: 'Chen Hsong',
    machineTonnage: '328T',
    injectionVolume: '480g',
    quantity: '2',
    usageArea: 'Injection Workshop',
  },
  {
    no: '23',
    brand: 'Chen Hsong',
    machineTonnage: '468T',
    injectionVolume: '450g',
    quantity: '2',
    usageArea: 'Injection Workshop',
  },
  {
    no: '24',
    brand: 'FUQiangXin',
    machineTonnage: '280T',
    injectionVolume: '251g',
    quantity: '1',
    usageArea: 'Injection Workshop',
  },
  {
    no: '25',
    brand: 'FUQiangXin',
    machineTonnage: '400T',
    injectionVolume: '511g',
    quantity: '1',
    usageArea: 'Injection Workshop',
  },
  {
    no: '26',
    brand: 'FUQiangXin',
    machineTonnage: '550T',
    injectionVolume: '618g',
    quantity: '1',
    usageArea: 'Injection Workshop',
  },
  {
    no: '27',
    brand: 'YIZUMI',
    machineTonnage: '400T',
    injectionVolume: '1377g',
    quantity: '1',
    usageArea: 'Injection Workshop',
  },
  {
    no: '28',
    brand: 'YIZUMI',
    machineTonnage: '650T',
    injectionVolume: '2446g',
    quantity: '1',
    usageArea: 'Injection Workshop',
  },
  {
    no: '29',
    brand: 'YIZUMI',
    machineTonnage: '800T',
    injectionVolume: '3468g',
    quantity: '1',
    usageArea: 'Injection Workshop',
  },
  {
    no: '30',
    brand: 'YIZUMI',
    machineTonnage: '1100T',
    injectionVolume: '4636g',
    quantity: '1',
    usageArea: 'Injection Workshop',
  },
  {
    no: '31',
    brand: 'YIZUMI',
    machineTonnage: '1850T',
    injectionVolume: '7399g',
    quantity: '1',
    usageArea: 'Injection Workshop',
  },
];
